### ISSUE TITLE
Error while generating an image from rxn file

### ISSUE THREAD

**Issue by parit** [asad/ReactionDecoder#12]
Hi, 
I am trying to read an rxn file and simple generate a png out of it. 

`
RXNFileImporter importer = new RXNFileImporter();
importer.readFile("29544.rxn");
ImageGenerator.LeftToRightReactionCenterImage(importer.getReaction(), "29544", "/home/rxn");`

and am getting the following error: 

`
Exception in thread "main" java.lang.IllegalArgumentException: Container has no bonds.
	at org.openscience.cdk.geometry.GeometryUtil.getBondLengthMedian(GeometryUtil.java:1671)
	at org.openscience.cdk.geometry.GeometryUtil.getScaleFactor(GeometryUtil.java:899)
	at uk.ac.ebi.reactionblast.graphics.direct.layout.LinearMoleculeSetLayout.layout(LinearMoleculeSetLayout.java:120)
	at uk.ac.ebi.reactionblast.graphics.direct.layout.LeftToRightReactionLayout.layout(LeftToRightReactionLayout.java:75)
	at uk.ac.ebi.reactionblast.graphics.direct.layout.LeftToRightReactionLayout.layout(LeftToRightReactionLayout.java:1)
	at uk.ac.ebi.reactionblast.graphics.direct.DirectReactionDrawer.getExactReactionBounds(DirectReactionDrawer.java:733)
	at uk.ac.ebi.reactionblast.graphics.direct.DirectRBLastReactionDrawer.drawRBlastReaction(DirectRBLastReactionDrawer.java:134)
	at uk.ac.ebi.reactionblast.tools.ImageGenerator.makeReactionCenterHighlightedReactionToFile(ImageGenerator.java:218)
	at uk.ac.ebi.reactionblast.tools.ImageGenerator.LeftToRightReactionCenterImage(ImageGenerator.java:458)
	at org.expasy.Runner.main(Runner.java:21)
`

Closer inspection led me to the following line in uk.ac.ebi.reactionblast.graphics.direct.layout.LinearMoleculeSetLayout.layout   method.

`scaleMolecule(molecule, getScaleFactor(molecule, bondLength));`

getScaleFactor fails for H ion present in the reaction (since it has no bonds). Not sure whats the best way to fix this. Please help. 

[29544.rxn.txt](https://github.com/asad/ReactionDecoder/files/3788994/29544.rxn.txt)

**Comment by asad** [comment]
All fixed, please try 2.4.1
