### ISSUE TITLE
"main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by rmtfleming** [asad/ReactionDecoder#29]
With older and also the later version, I get the error below. Any suggestions?

https://github.com/asad/ReactionDecoder/releases/download/v2.5.0/rdt-2.5.0-SNAPSHOT-jar-with-dependencies.jar

timeout 1800s java -jar rdtAlgorithm.jar -Q RXN -q "G6PDH2r.rxn" -g -j AAM -f TEXT

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: uk/ac/ebi/aamtool/ReactionDecoder has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

$java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
$ javac -version
javac 1.8.0_131

**Comment by johnmay** [comment]
You need to use Java 11 (or 17).

It is built targeting Java 11: https://github.com/asad/ReactionDecoder/blob/master/pom.xml#L12-L13

https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers
