### ISSUE TITLE
compile the code, not work well

### ISSUE THREAD

**Issue by twz915** [asad/ReactionDecoder#3]
When I compile the code according to the description.
```bash
ant clean
ant compile
ant jar
```
I use the `ReactionDecoder.jar` in the `dist` folder

When I run the following demo, it throws exception:

tu@mac ~/recently/ReactionDecoder/bin (master*) $ java -jar ReactionDecoder.jar -Q SMI -q "C.C>>CC" -g -j AAM -f TEXT
Exception in thread "main" java.lang.NoClassDefFoundError: org/openscience/cdk/exception/InvalidSmilesException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
	at java.lang.Class.getMethod0(Class.java:3010)
	at java.lang.Class.getMethod(Class.java:1776)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.openscience.cdk.exception.InvalidSmilesException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by johnmay** [comment]
Confirmed

**Comment by johnmay** [comment]
This needs fixing/documenting but you can resolve it by specifying the lib and dist on the classpath and calling the main class explicitly.

```java -cp dist/*:lib/* aamtool.ReactionDecoder```

**Comment by twz915** [comment]
I am a newbie at Java. I want to change some code in ReactionDecoder to get `Atom Atom Mapping` **without the unchanged atoms**. Could you give me some ideas to do this?

**Comment by johnmay** [comment]
Can't personally help with that... Asad may be able to advise. Essentially you want the option to specify the type of map produced. Generally there is: 'complete', 'changing', 'matching': https://docs.chemaxon.com/display/AUT/AutoMapper+User's+Guide

Since I think ReactionDecoder always produces the 'matching' style of atom map it's possible to derive the 'changing' style in post processing.

**Comment by twz915** [comment]
ReactionDecoder is very powerful tool. Thanks for your quick response. I'll try to use `ChemAxon` to do such a thing.

**Comment by asad** [comment]
Its simple, you could get all the changing atoms using the following code.
      
      a) Get the best solution from the reaction ReactionMechanismTool 
      b) Call the  bondChangeAnnotator.getReactionCenterSet() to get list of atoms part of the reaction centre (Change).

        Map<IAtom, IAtom> reactionCenterMap = new HashMap<>();
        for (IAtom atom : bondChangeAnnotator.getReactionCenterSet()) {
            if (!atom.getSymbol().equals("H")) {
                reactionCenterMap.put(atom, bondChangeAnnotator.getMappingMap().get(atom));
            }
        }
